/* Languages: the 22 scheduled languages of India (+ English).
   Each entry carries the native name, the English name, the BCP-47 tag used
   for the browser voice, a native greeting, and an optional UI-string pack.
   Any language without a pack falls back to English labels while still using
   its own recogniser / voice for speech. */

const MK_LANGS = [
  { code: "en",  name: "English",   native: "English",    speech: "en-IN", greet: "Namaste. Welcome." },
  { code: "as",  name: "Assamese",  native: "অসমীয়া",      speech: "as-IN", greet: "নমস্কাৰ। স্বাগতম।" },
  { code: "bn",  name: "Bengali",   native: "বাংলা",        speech: "bn-IN", greet: "নমস্কার। স্বাগতম।" },
  { code: "brx", name: "Bodo",      native: "बड़ो",         speech: "brx-IN", greet: "नमस्कार। बरायबा।" },
  { code: "doi", name: "Dogri",     native: "डोगरी",        speech: "doi-IN", greet: "नमस्कार। स्वागत ऐ।" },
  { code: "gu",  name: "Gujarati",  native: "ગુજરાતી",      speech: "gu-IN", greet: "નમસ્તે. સ્વાગત છે." },
  { code: "hi",  name: "Hindi",     native: "हिन्दी",        speech: "hi-IN", greet: "नमस्ते। स्वागत है।" },
  { code: "kn",  name: "Kannada",   native: "ಕನ್ನಡ",        speech: "kn-IN", greet: "ನಮಸ್ಕಾರ. ಸ್ವಾಗತ." },
  { code: "ks",  name: "Kashmiri",  native: "کٲشُر",         speech: "ks-IN", greet: "نَمَسکار۔ خوش آمدید۔" },
  { code: "kok", name: "Konkani",   native: "कोंकणी",       speech: "kok-IN", greet: "नमस्कार. येवकार." },
  { code: "mai", name: "Maithili",  native: "मैथिली",        speech: "mai-IN", greet: "नमस्कार। स्वागत अछि।" },
  { code: "ml",  name: "Malayalam", native: "മലയാളം",       speech: "ml-IN", greet: "നമസ്കാരം. സ്വാഗതം." },
  { code: "mni", name: "Manipuri",  native: "মৈতৈলোন্",      speech: "mni-IN", greet: "নমস্কার। স্বাগতম।" },
  { code: "mr",  name: "Marathi",   native: "मराठी",        speech: "mr-IN", greet: "नमस्कार. स्वागत आहे." },
  { code: "ne",  name: "Nepali",    native: "नेपाली",       speech: "ne-IN", greet: "नमस्कार। स्वागत छ।" },
  { code: "or",  name: "Odia",      native: "ଓଡ଼ିଆ",         speech: "or-IN", greet: "ନମସ୍କାର। ସ୍ୱାଗତ।" },
  { code: "pa",  name: "Punjabi",   native: "ਪੰਜਾਬੀ",       speech: "pa-IN", greet: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ। ਜੀ ਆਇਆਂ ਨੂੰ।" },
  { code: "sa",  name: "Sanskrit",  native: "संस्कृतम्",     speech: "sa-IN", greet: "नमस्ते। स्वागतम्।" },
  { code: "sat", name: "Santali",   native: "ᱥᱟᱱᱛᱟᱲᱤ",       speech: "sat-IN", greet: "ᱡᱚᱦᱟᱨ। ᱥᱟᱨᱦᱟᱣ।" },
  { code: "sd",  name: "Sindhi",    native: "سنڌي",          speech: "sd-IN", greet: "نمسڪار. ڀلي ڪري آيا." },
  { code: "ta",  name: "Tamil",     native: "தமிழ்",         speech: "ta-IN", greet: "வணக்கம். வரவேற்கிறோம்." },
  { code: "te",  name: "Telugu",    native: "తెలుగు",        speech: "te-IN", greet: "నమస్కారం. స్వాగతం." },
  { code: "ur",  name: "Urdu",      native: "اردو",          speech: "ur-IN", greet: "السلام علیکم۔ خوش آمدید۔" },
];

/* UI packs. Keys are stable; missing keys fall back to English. */
const MK_UI = {
  en: {
    tagline: "Tell us your story before you see the doctor",
    chooseLang: "Choose your language",
    langNote: "Tap your language. The kiosk will speak to you and listen to your answers.",
    begin: "Begin",
    consentHead: "Before we begin — your consent",
    agree: "I have read and understood this notice",
    listening: "Listening to you…",
    speakNow: "Speak your answer",
    stopListening: "Tap to stop",
    speaking: "Speaking…",
    hearAgain: "Hear again",
    yourAnswer: "Your answer",
    next: "Continue",
    back: "Back",
    skip: "Skip this question",
    correct: "Correct",
    change: "Change",
    confirm: "Confirm and finish",
    tapWhere: "Tap where it hurts on the body picture",
  },
  hi: {
    tagline: "डॉक्टर से मिलने से पहले अपनी बात बताइए",
    chooseLang: "अपनी भाषा चुनिए",
    langNote: "अपनी भाषा चुनिए। कियोस्क आपसे बोलेगा और आपके जवाब सुनेगा।",
    begin: "शुरू कीजिए",
    consentHead: "शुरू करने से पहले — आपकी सहमति",
    agree: "मैंने यह सूचना पढ़ और समझ ली है",
    listening: "आपकी बात सुन रहे हैं…",
    speakNow: "अपना जवाब बोलिए",
    stopListening: "रोकने के लिए दबाइए",
    speaking: "बोल रहे हैं…",
    hearAgain: "फिर से सुनिए",
    yourAnswer: "आपका जवाब",
    next: "आगे बढ़िए",
    back: "पीछे",
    skip: "यह सवाल छोड़ दीजिए",
    correct: "सही है",
    change: "बदलिए",
    confirm: "पुष्टि कीजिए",
    tapWhere: "शरीर की तस्वीर पर दर्द वाली जगह दबाइए",
  },
  bn: {
    tagline: "ডাক্তার দেখানোর আগে আপনার কথা জানান",
    chooseLang: "আপনার ভাষা বেছে নিন",
    langNote: "আপনার ভাষা বাছুন। কিয়স্ক আপনার সঙ্গে কথা বলবে ও আপনার উত্তর শুনবে।",
    begin: "শুরু করুন",
    consentHead: "শুরুর আগে — আপনার সম্মতি",
    agree: "আমি এই বিজ্ঞপ্তি পড়েছি ও বুঝেছি",
    listening: "আপনার কথা শুনছি…",
    speaking: "বলছি…",
    hearAgain: "আবার শুনুন",
    yourAnswer: "আপনার উত্তর",
    next: "এগিয়ে যান",
    back: "পিছনে",
    skip: "এই প্রশ্নটি বাদ দিন",
    correct: "ঠিক আছে",
    change: "বদলান",
    confirm: "নিশ্চিত করুন",
    tapWhere: "শরীরের ছবিতে যেখানে ব্যথা সেখানে চাপ দিন",
  },
  ta: {
    tagline: "மருத்துவரைப் பார்ப்பதற்கு முன் உங்கள் கதையைச் சொல்லுங்கள்",
    chooseLang: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    langNote: "உங்கள் மொழியைத் தட்டவும். கியோஸ்க் பேசும், உங்கள் பதில்களைக் கேட்கும்.",
    begin: "தொடங்கு",
    consentHead: "தொடங்கும் முன் — உங்கள் ஒப்புதல்",
    agree: "இந்த அறிவிப்பைப் படித்து புரிந்துகொண்டேன்",
    listening: "உங்களைக் கேட்கிறோம்…",
    speaking: "பேசுகிறோம்…",
    hearAgain: "மீண்டும் கேட்க",
    yourAnswer: "உங்கள் பதில்",
    next: "தொடரவும்",
    back: "பின்",
    skip: "இந்தக் கேள்வியைத் தவிர்",
    correct: "சரி",
    change: "மாற்று",
    confirm: "உறுதிப்படுத்து",
    tapWhere: "உடல் படத்தில் வலி இருக்கும் இடத்தைத் தட்டவும்",
  },
  te: {
    tagline: "డాక్టర్‌ను కలిసే ముందు మీ కథ చెప్పండి",
    chooseLang: "మీ భాషను ఎంచుకోండి",
    langNote: "మీ భాషను నొక్కండి. కియోస్క్ మాట్లాడుతుంది, మీ సమాధానాలు వింటుంది.",
    begin: "ప్రారంభించు",
    consentHead: "ప్రారంభించే ముందు — మీ అనుమతి",
    agree: "ఈ నోటీసును చదివి అర్థం చేసుకున్నాను",
    listening: "మీ మాటలు వింటున్నాము…",
    speaking: "మాట్లాడుతున్నాము…",
    hearAgain: "మళ్లీ వినండి",
    yourAnswer: "మీ సమాధానం",
    next: "కొనసాగించు",
    back: "వెనుక",
    skip: "ఈ ప్రశ్నను దాటవేయి",
    correct: "సరైనది",
    change: "మార్చు",
    confirm: "నిర్ధారించు",
    tapWhere: "శరీర చిత్రంలో నొప్పి ఉన్న చోట నొక్కండి",
  },
  mr: {
    tagline: "डॉक्टरांना भेटण्यापूर्वी तुमची गोष्ट सांगा",
    chooseLang: "तुमची भाषा निवडा",
    langNote: "तुमची भाषा निवडा. कियोस्क बोलेल आणि तुमची उत्तरे ऐकेल.",
    begin: "सुरू करा",
    consentHead: "सुरू करण्यापूर्वी — तुमची संमती",
    agree: "मी ही सूचना वाचली आणि समजली",
    listening: "तुमचे ऐकत आहोत…",
    speaking: "बोलत आहोत…",
    hearAgain: "पुन्हा ऐका",
    yourAnswer: "तुमचे उत्तर",
    next: "पुढे",
    back: "मागे",
    skip: "हा प्रश्न वगळा",
    correct: "बरोबर",
    change: "बदला",
    confirm: "पुष्टी करा",
    tapWhere: "शरीराच्या चित्रात दुखणारी जागा दाबा",
  },
  gu: {
    tagline: "ડૉક્ટરને મળતા પહેલાં તમારી વાત કહો",
    chooseLang: "તમારી ભાષા પસંદ કરો",
    langNote: "તમારી ભાષા પસંદ કરો. કિઓસ્ક બોલશે અને તમારા જવાબ સાંભળશે.",
    begin: "શરૂ કરો",
    consentHead: "શરૂ કરતાં પહેલાં — તમારી સંમતિ",
    agree: "મેં આ સૂચના વાંચી અને સમજી",
    listening: "તમારી વાત સાંભળી રહ્યા છીએ…",
    speaking: "બોલી રહ્યા છીએ…",
    hearAgain: "ફરી સાંભળો",
    yourAnswer: "તમારો જવાબ",
    next: "આગળ",
    back: "પાછળ",
    skip: "આ પ્રશ્ન છોડો",
    correct: "સાચું",
    change: "બદલો",
    confirm: "પુષ્ટિ કરો",
    tapWhere: "શરીરના ચિત્રમાં દુખતી જગ્યા દબાવો",
  },
  kn: {
    tagline: "ವೈದ್ಯರನ್ನು ಭೇಟಿಯಾಗುವ ಮೊದಲು ನಿಮ್ಮ ಕಥೆ ಹೇಳಿ",
    chooseLang: "ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    langNote: "ನಿಮ್ಮ ಭಾಷೆ ಒತ್ತಿ. ಕಿಯೋಸ್ಕ್ ಮಾತನಾಡುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ಉತ್ತರ ಕೇಳುತ್ತದೆ.",
    begin: "ಪ್ರಾರಂಭಿಸಿ",
    consentHead: "ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು — ನಿಮ್ಮ ಒಪ್ಪಿಗೆ",
    agree: "ಈ ಸೂಚನೆಯನ್ನು ಓದಿ ಅರ್ಥ ಮಾಡಿಕೊಂಡಿದ್ದೇನೆ",
    listening: "ನಿಮ್ಮ ಮಾತು ಕೇಳುತ್ತಿದ್ದೇವೆ…",
    speaking: "ಮಾತನಾಡುತ್ತಿದ್ದೇವೆ…",
    hearAgain: "ಮತ್ತೆ ಕೇಳಿ",
    yourAnswer: "ನಿಮ್ಮ ಉತ್ತರ",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    skip: "ಈ ಪ್ರಶ್ನೆ ಬಿಡಿ",
    correct: "ಸರಿ",
    change: "ಬದಲಿಸಿ",
    confirm: "ದೃಢಪಡಿಸಿ",
    tapWhere: "ದೇಹದ ಚಿತ್ರದಲ್ಲಿ ನೋವಿರುವ ಜಾಗ ಒತ್ತಿ",
  },
  ml: {
    tagline: "ഡോക്ടറെ കാണുന്നതിന് മുമ്പ് നിങ്ങളുടെ കാര്യം പറയൂ",
    chooseLang: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കൂ",
    langNote: "ഭാഷ തിരഞ്ഞെടുക്കൂ. കിയോസ്ക് സംസാരിക്കും, ഉത്തരങ്ങൾ കേൾക്കും.",
    begin: "തുടങ്ങൂ",
    consentHead: "തുടങ്ങുന്നതിന് മുമ്പ് — നിങ്ങളുടെ സമ്മതം",
    agree: "ഈ അറിയിപ്പ് വായിച്ച് മനസ്സിലാക്കി",
    listening: "നിങ്ങളെ കേൾക്കുന്നു…",
    speaking: "സംസാരിക്കുന്നു…",
    hearAgain: "വീണ്ടും കേൾക്കൂ",
    yourAnswer: "നിങ്ങളുടെ ഉത്തരം",
    next: "തുടരൂ",
    back: "പിന്നോട്ട്",
    skip: "ഈ ചോദ്യം ഒഴിവാക്കൂ",
    correct: "ശരി",
    change: "മാറ്റൂ",
    confirm: "സ്ഥിരീകരിക്കൂ",
    tapWhere: "ശരീര ചിത്രത്തിൽ വേദനയുള്ള ഭാഗത്ത് അമർത്തൂ",
  },
  pa: {
    tagline: "ਡਾਕਟਰ ਨੂੰ ਮਿਲਣ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੀ ਗੱਲ ਦੱਸੋ",
    chooseLang: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    langNote: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ। ਕਿਓਸਕ ਬੋਲੇਗਾ ਅਤੇ ਤੁਹਾਡੇ ਜਵਾਬ ਸੁਣੇਗਾ।",
    begin: "ਸ਼ੁਰੂ ਕਰੋ",
    consentHead: "ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ — ਤੁਹਾਡੀ ਸਹਿਮਤੀ",
    agree: "ਮੈਂ ਇਹ ਸੂਚਨਾ ਪੜ੍ਹ ਲਈ ਅਤੇ ਸਮਝ ਲਈ",
    listening: "ਤੁਹਾਡੀ ਗੱਲ ਸੁਣ ਰਹੇ ਹਾਂ…",
    speaking: "ਬੋਲ ਰਹੇ ਹਾਂ…",
    hearAgain: "ਦੁਬਾਰਾ ਸੁਣੋ",
    yourAnswer: "ਤੁਹਾਡਾ ਜਵਾਬ",
    next: "ਅੱਗੇ",
    back: "ਪਿੱਛੇ",
    skip: "ਇਹ ਸਵਾਲ ਛੱਡੋ",
    correct: "ਸਹੀ",
    change: "ਬਦਲੋ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    tapWhere: "ਸਰੀਰ ਦੀ ਤਸਵੀਰ ਵਿੱਚ ਦਰਦ ਵਾਲੀ ਥਾਂ ਦਬਾਓ",
  },
  or: {
    tagline: "ଡାକ୍ତରଙ୍କୁ ଦେଖିବା ପୂର୍ବରୁ ଆପଣଙ୍କ କଥା କୁହନ୍ତୁ",
    chooseLang: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
    langNote: "ଭାଷା ବାଛନ୍ତୁ। କିଓସ୍କ କହିବ ଏବଂ ଆପଣଙ୍କ ଉତ୍ତର ଶୁଣିବ।",
    begin: "ଆରମ୍ଭ କରନ୍ତୁ",
    consentHead: "ଆରମ୍ଭ ପୂର୍ବରୁ — ଆପଣଙ୍କ ସମ୍ମତି",
    agree: "ମୁଁ ଏହି ସୂଚନା ପଢ଼ି ବୁଝିଛି",
    listening: "ଆପଣଙ୍କ କଥା ଶୁଣୁଛୁ…",
    speaking: "କହୁଛୁ…",
    hearAgain: "ପୁଣି ଶୁଣନ୍ତୁ",
    yourAnswer: "ଆପଣଙ୍କ ଉତ୍ତର",
    next: "ଆଗକୁ",
    back: "ପଛକୁ",
    skip: "ଏହି ପ୍ରଶ୍ନ ଛାଡ଼ନ୍ତୁ",
    correct: "ଠିକ୍",
    change: "ବଦଳାନ୍ତୁ",
    confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ",
    tapWhere: "ଶରୀର ଚିତ୍ରରେ ଯେଉଁଠି ଯନ୍ତ୍ରଣା ସେଠାରେ ଦବାନ୍ତୁ",
  },
  ur: {
    tagline: "ڈاکٹر سے ملنے سے پہلے اپنی بات بتائیے",
    chooseLang: "اپنی زبان منتخب کیجیے",
    langNote: "اپنی زبان منتخب کیجیے۔ کیوسک بولے گا اور آپ کے جواب سنے گا۔",
    begin: "شروع کیجیے",
    consentHead: "شروع کرنے سے پہلے — آپ کی رضامندی",
    agree: "میں نے یہ اطلاع پڑھ اور سمجھ لی",
    listening: "آپ کی بات سن رہے ہیں…",
    speaking: "بول رہے ہیں…",
    hearAgain: "دوبارہ سنیے",
    yourAnswer: "آپ کا جواب",
    next: "آگے",
    back: "پیچھے",
    skip: "یہ سوال چھوڑ دیجیے",
    correct: "درست",
    change: "تبدیل کریں",
    confirm: "تصدیق کریں",
    tapWhere: "جسم کی تصویر میں جہاں درد ہے وہاں دبائیے",
  },
  as: {
    tagline: "ডাক্তৰক লগ পোৱাৰ আগতে আপোনাৰ কথা কওক",
    chooseLang: "আপোনাৰ ভাষা বাছনি কৰক",
    langNote: "ভাষা বাছনি কৰক। কিয়স্কে ক'ব আৰু আপোনাৰ উত্তৰ শুনিব।",
    begin: "আৰম্ভ কৰক",
    consentHead: "আৰম্ভ কৰাৰ আগতে — আপোনাৰ সন্মতি",
    agree: "মই এই জাননী পঢ়ি বুজি লৈছোঁ",
    listening: "আপোনাৰ কথা শুনি আছোঁ…",
    speaking: "কৈ আছোঁ…",
    hearAgain: "পুনৰ শুনক",
    yourAnswer: "আপোনাৰ উত্তৰ",
    next: "আগবাঢ়ক",
    back: "পিছলৈ",
    skip: "এই প্ৰশ্ন এৰি দিয়ক",
    correct: "শুদ্ধ",
    change: "সলনি কৰক",
    confirm: "নিশ্চিত কৰক",
    tapWhere: "শৰীৰৰ ছবিত বিষ থকা ঠাইত টিপক",
  },
  ne: {
    tagline: "डाक्टरलाई भेट्नु अघि आफ्नो कुरा भन्नुहोस्",
    chooseLang: "आफ्नो भाषा छान्नुहोस्",
    langNote: "आफ्नो भाषा छान्नुहोस्। कियोस्क बोल्छ र तपाईंको जवाफ सुन्छ।",
    begin: "सुरु गर्नुहोस्",
    consentHead: "सुरु गर्नु अघि — तपाईंको सहमति",
    agree: "मैले यो सूचना पढेँ र बुझेँ",
    listening: "तपाईंको कुरा सुन्दैछौं…",
    speaking: "बोल्दैछौं…",
    hearAgain: "फेरि सुन्नुहोस्",
    yourAnswer: "तपाईंको जवाफ",
    next: "अगाडि",
    back: "पछाडि",
    skip: "यो प्रश्न छोड्नुहोस्",
    correct: "ठीक",
    change: "बदल्नुहोस्",
    confirm: "पुष्टि गर्नुहोस्",
    tapWhere: "शरीरको चित्रमा दुख्ने ठाउँमा थिच्नुहोस्",
  },
};

function mkLang(code) {
  return MK_LANGS.find((l) => l.code === code) || MK_LANGS[0];
}

function mkT(key, code) {
  const pack = MK_UI[code] || {};
  if (pack[key] != null) return pack[key];
  return (MK_UI.en[key] != null) ? MK_UI.en[key] : key;
}
