"""C3 - Renderer: the store-once/render-many views (doc/04).

Deterministic template rendering from the CaseSummary canon. NO LLM in v1 -
by design (doc/15 section 2: hallucination measurement for LLM summaries is
contested, 35% lexical vs 9% inference-aware, arXiv:2604.14829; reasoning
modes hurt fidelity, arXiv:2605.24902; 2026-09-11 /last30days validation:
r/healthIT scribe-AI notes "came out generic, kept getting terminology wrong,
providers still had to rewrite half of it anyway"). Every rendered line
carries the canon field ids it came from, so the eval harness can prove
no-fabrication by construction.

Views:
- SOAP note (physician-facing; doc/04 section 1 mapping)
- OLD CARTS re-organization of the same SOCRATES data (doc/04 insight)
- patient read-back, bilingual (en/hi), for the confirm step
"""
from __future__ import annotations

from .contracts import HistoryBundle, Slot
from .merger import CaseSummary

# ---------------------------------------------------------------- label tables

SOCRATES_LABELS = {
    "site": {"en": "Site", "hi": "जगह"},
    "onset": {"en": "Onset", "hi": "शुरुआत"},
    "character": {"en": "Character", "hi": "प्रकार"},
    "radiation": {"en": "Radiation", "hi": "फैलना"},
    "associations": {"en": "Associations", "hi": "साथ में"},
    "timing": {"en": "Timing", "hi": "समय"},
    "exacerbating": {"en": "Exacerbating/relieving", "hi": "बढ़ता/घटता"},
    "severity": {"en": "Severity", "hi": "तीव्रता"},
}

OLD_CARTS_ORDER = {          # doc/04: same data reorganized for documentation
    "onset": "O - Onset",
    "site": "L - Location",
    "timing": "D - Duration",
    "character": "C - Character",
    "exacerbating": "A - Aggravating/Alleviating",
    "radiation": "R - Radiation",
    "timing2": "T - Temporal pattern",
    "severity": "S - Severity",
}

STATE_LABELS = {
    "needs_review": {"en": "needs review", "hi": "जाँच बाकी"},
    "not_answered": {"en": "not answered (patient will tell doctor)",
                      "hi": "जवाब नहीं दिया (मरीज़ डॉक्टर को बताएँगे)"},
    "not_elicited": {"en": "not asked (session ended early)",
                     "hi": "पूछा नहीं गया (सत्र जल्दी बंद हुआ)"},
}

PROXY_TAG = {"en": "stated by attendant", "hi": "परिचारक ने बताया"}
VOICE_TAG = {"en": "voice - original words kept", "hi": "आवाज़ - मूल शब्द रखे गए"}
DOCTOR_ONLY = {
    "en": "Assessment & Plan - physician only. Not generated by the kiosk.",
    "hi": "मूल्यांकन और योजना - केवल चिकित्सक। कियोस्क इसे नहीं बनाता।",
}


# ------------------------------------------------------------------- line model

class Line:
    """One rendered line with its canon provenance (field ids)."""

    __slots__ = ("text", "src")

    def __init__(self, text: str, src: list[str] | None = None):
        self.text = text
        self.src = src or []

    def to_dict(self) -> dict:
        return {"text": self.text, "src": self.src}


def _slot_line(slot: Slot, labels: dict, lang: str = "en") -> Line:
    label = labels.get(slot.key, {}).get(lang, slot.key)
    return Line(f"{label}: {slot.value}", [f"A:{slot.key}"])


def _tag(slot: Slot, lang: str = "en") -> str:
    tag = ""
    if slot.by == "proxy":
        tag += f" [{PROXY_TAG[lang]}]"
    if slot.voice:
        tag += f" [{VOICE_TAG[lang]}]"
    if slot.state == "needs_review":
        tag += f" [{STATE_LABELS['needs_review'][lang]}]"
    return tag


# ------------------------------------------------------------------- SOAP view

def render_soap(case: CaseSummary) -> dict:
    """Physician-facing SOAP note from the canon (doc/04 section 1 mapping)."""
    h = case.history
    S, O = [], []

    # -- S: CC + HPI + past/surgical + meds + allergies + family/social + ROS + ICE
    cc = h.complaint.get("free_text") or h.complaint.get("term") or "(not stated)"
    cc_src = ["A:complaint"]
    S.append(Line(f"Chief complaint (patient's words): {cc}", cc_src))

    hpi_parts = [_slot_line(s, SOCRATES_LABELS) for s in h.captured_slots()
                 if s.key in SOCRATES_LABELS]
    for ln in hpi_parts:
        ln.text += _tag(next(s for s in h.captured_slots() if f"A:{s.key}" in ln.src))
        S.append(ln)

    if h.pmh:
        S.append(Line("Past history: " + "; ".join(
            p.get("text", "") for p in h.pmh), ["A:pmh"]))
    if h.allergies:
        S.append(Line("Allergies: " + "; ".join(
            a.get("text", "") for a in h.allergies), ["A:allergies"]))
    if case.meds:
        S.append(Line("Medications: " + "; ".join(
            _med_str(m) for m in case.meds),
            [m.fid for m in case.meds]))
    if h.family:
        S.append(Line("Family history: " + "; ".join(
            f.get("text", "") for f in h.family), ["A:family"]))
    if h.social:
        S.append(Line("Social history: " + "; ".join(
            s.get("text", "") for s in h.social), ["A:social"]))
    pos = [r for r in h.ros if r.get("positive")]
    neg = [r for r in h.ros if not r.get("positive") and r.get("state") == "captured"]
    if pos:
        S.append(Line("ROS pertinent positives: " + "; ".join(
            r.get("symptom", "") for r in pos), ["A:ros"]))
    if neg:
        S.append(Line("ROS pertinent negatives: " + "; ".join(
            r.get("symptom", "") for r in neg), ["A:ros"]))
    for key, slot in h.ice.items():
        if slot.rendered:
            S.append(Line(f"ICE {key}: {slot.value}" + _tag(slot), [f"A:ice.{key}"]))

    # -- O: document-derived data only; vitals explicitly deferred to triage
    if case.labs:
        O.append(Line("Prior results (from patient's papers):", []))
        for lab in case.labs:
            flag = f" [{lab.abnormal.upper()} ({lab.range_note})]" if lab.abnormal else ""
            verify = " [verify]" if lab.verify else ""
            O.append(Line(f"  {lab.label()}{flag}{verify}", [lab.fid]))
    if case.dx:
        O.append(Line("Documented conditions (from papers): " + "; ".join(
            d["text"] for d in case.dx), [d["fid"] for d in case.dx]))
    O.append(Line("Vitals / examination: to be recorded at consultation", []))

    # -- A / P: physician-only, never generated (locked in the demo UI too)
    A = [Line(DOCTOR_ONLY["en"], [])]
    P = [Line("Plan - physician only. Draft slots left blank by design.", [])]

    # -- honesty block: states of every elicitation slot (anti-fabrication)
    gaps = _gap_lines(h)
    return {
        "view": "soap",
        "S": [l.to_dict() for l in S],
        "O": [l.to_dict() for l in O],
        "A": [l.to_dict() for l in A],
        "P": [l.to_dict() for l in P],
        "gaps": [l.to_dict() for l in gaps],
    }


def _med_str(m) -> str:
    src = "+".join(m.sources)
    note = f" ({m.reason})" if m.reason else ""
    return f"{m.label()} [{src}]{note}"


def _gap_lines(h: HistoryBundle) -> list[Line]:
    """Explicit not_answered / not_elicited slots - the honesty block."""
    out = []
    for key, slot in list(h.socrates.items()) + list(h.ice.items()):
        if slot.state in ("not_answered", "not_elicited"):
            label = SOCRATES_LABELS.get(key, {}).get("en", key)
            out.append(Line(f"{label}: {STATE_LABELS[slot.state]['en']}",
                            [f"A:{key}"]))
    return out


# --------------------------------------------------------------- OLD CARTS view

def render_oldcarts(case: CaseSummary) -> dict:
    """Same SOCRATES data reorganized for documentation (doc/04 key insight:
    SOCRATES elicits, OLD CARTS documents - store once, render many)."""
    h = case.history
    sections: dict[str, list[dict]] = {}
    for field, heading in OLD_CARTS_ORDER.items():
        key = "timing" if field == "timing2" else field
        slot = h.socrates.get(key)
        if slot is None:
            continue
        if slot.rendered:
            sections.setdefault(heading, []).append(
                Line(slot.value + _tag(slot), [f"A:{key}"]).to_dict())
        else:
            sections.setdefault(heading, []).append(
                Line(STATE_LABELS.get(slot.state, {}).get("en", slot.state),
                     [f"A:{key}"]).to_dict())
    return {"view": "oldcarts", "sections": sections}


# ---------------------------------------------------------------- read-back view

def render_readback(case: CaseSummary, lang: str = "en") -> dict:
    """Patient-facing confirm summary, bilingual label dictionary.

    Values are passed through verbatim (patient's own words are the point of
    the read-back); labels render in the requested language. Deterministic
    dictionary translation only - no cloud MT (Bhashini stays blocked-risk,
    doc/09; IndicTrans2 is the product-track offline lane, doc/15 section 5)."""
    h = case.history
    lines: list[dict] = []

    def add(text: str, src: list[str]) -> None:
        lines.append(Line(text, src).to_dict())

    cc = h.complaint.get("free_text") or h.complaint.get("term") or ""
    if cc:
        lbl = {"en": "Your problem", "hi": "आपकी समस्या"}[lang]
        add(f"{lbl}: {cc}", ["A:complaint"])

    for s in h.captured_slots():
        label = SOCRATES_LABELS.get(s.key, {}).get(lang, s.key)
        if s.key.startswith("ice."):
            label = {"ideas": {"en": "What you think it is", "hi": "आपको क्या लगता है"},
                     "concerns": {"en": "What worries you", "hi": "आपको किस बात की चिंता है"},
                     "expectations": {"en": "What you want today",
                                      "hi": "आज आप क्या चाहते हैं"}}.get(
                s.key.split(".", 1)[1], {}).get(lang, s.key)
        add(f"{label}: {s.value}" + _tag(s, lang), [f"A:{s.key}"])

    if h.allergies:
        lbl = {"en": "Allergies", "hi": "एलर्जी"}[lang]
        add(f"{lbl}: " + "; ".join(a.get("text", "") for a in h.allergies),
            ["A:allergies"])
    if case.meds:
        lbl = {"en": "Medicines you take", "hi": "आपकी दवाएँ"}[lang]
        add(f"{lbl}: " + "; ".join(m.label() for m in case.meds),
            [m.fid for m in case.meds])
    if h.social:
        lbl = {"en": "Habits", "hi": "आदतें"}[lang]
        add(f"{lbl}: " + "; ".join(s.get("text", "") for s in h.social),
            ["A:social"])

    verify = {"en": "The doctor will check the papers that were scanned.",
              "hi": "डॉक्टर स्कैन किए काग़ज़ों की जाँच करेंगे।"}[lang]
    if case.documents and len(case.documents) > 0:
        add(verify, ["B:session"])

    return {"view": f"readback-{lang}", "lang": lang, "lines": lines}
